-- THIS IS A CONFIG FOR LAZY
-- The previous config from this file didn't work, so i had to use lazy for
-- settings

-- {
--   'saghen/blink.cmp',
--   dependencies = 'rafamadriz/friendly-snippets',
--   version = 'v0.*',
--   opts = {
--     keymap = {
--       preset = 'default',
--       ['<C-y>'] = {},
--       ['<Tab>'] = {
--         function(cmp)
--           if cmp.is_visible() then
--             return cmp.accept()
--           else
--             cmp.show()
--             return true
--           end
--         end,
--         'fallback'
--       },
--     },
--     appearance = {
--       use_nvim_cmp_as_default = true,
--       nerd_font_variant = 'mono'
--     },
--     signature = { enabled = true },
--     completion = {
--       menu = {
--         auto_show = false
--       },
--       ghost_text = {
--         enabled = false
--       }
--     }
--   },
-- }
