require("user.manager")
require("user.visual")
require("user.remap")
require("user.treesitter")
require("user.rose_pine")
require("user.commands")
require("user.lspconfig")
require("user.cmp")
-- require("user.builtin_completion")
require("user.luasnip")
require("user.functions")
require("user.telescope")
require("user.snippets")
require("user.dadbod")
require("user.project_root")
-- require('user.tab_rename_mksession')
require('user.tab_rename_resession')
-- require('user.markdown')
require('user.cmd-minibuffer')
require('user.shell-prompt')
require('user.quickfix')
require('user.autocmd')
require('user.compilation')
require('user.set')
require("user.resession")
-- require("user.sessions")
require("user.surround")
require("user.oil")
-- require("user.dirvish")
require("user.commenting")
-- require("user.commenting_plugin")
require("user.mini")
-- require("user.plugin_configs")


require('user.statusline')
-- require('user.statusline_simple')
-- require('user.lualine')
