 require("user.manager")
 require("user.visual")
 require("user.remap")
 require("user.treesitter")
 require("user.rose_pine")
 require("user.commands")
 require("user.lspconfig")
 require("user.cmp")
 require("user.luasnip")
 -- require("user.blink")
 require("user.functions")
 require("user.telescope")
 require("user.snippets")
 require("user.commenting")
 -- require("user.dadbod")
 require("user.surround") -- because i disabled keybindings on C-g
 require("user.project_root")
 require('user.tab_rename')
 require('user.markdown')
 require('user.cmd-minibuffer')
 require('user.shell-prompt')
 require('user.quickfix')
 require('user.autocmd')
 require('user.compilation')
 require('user.set')
 -- require('user.neogit')
 -- require('user.fugitive')
 -- require('user.hydra')
 -- require('user.oil')
 require("user.resession")
 require("user.dirvish")


require('user.statusline') -- the statusline code probably causes the cursor to dissappear
