#!/usr/bin/env sh

# Your existing script to set up workspaces and launch applications
# Create a tabbed container on workspace 1 and assign Alacritty instances to it
swaymsg 'workspace 1'
# swaymsg 'layout tabbed'
# swaymsg 'exec opera --enable-features=UseOzonePlatform --ozone-platform=wayland'
# swaymsg 'exec opera'
# swaymsg 'exec firefox'
swaymsg 'exec brave'

sleep 5

# Create a tabbed container on workspace 2 and assign browsers to it
swaymsg 'workspace 2'
# swaymsg 'layout tabbed'
# swaymsg 'exec vivaldi-stable'
# swaymsg 'exec vivaldi.vivaldi-stable'
# swaymsg 'exec librewolf-wayland'
# swaymsg 'exec librewolf'
# swaymsg 'exec firefox'
swaymsg 'exec vivaldi.vivaldi-stable --ozone-platform=wayland --enable-features=UseOzonePlatform --use-cmd-decoder=validating'
# swaymsg 'exec vivaldi --enable-features=UseOzonePlatform --ozone-platform=wayland'
# swaymsg 'exec alacritty'

sleep 7


swaymsg 'workspace 3'
# swaymsg 'exec alacritty -e tmux'
swaymsg 'exec emacs'
sleep 2
# swaymsg 'exec /opt/pycharm/bin/pycharm.sh'
swaymsg 'exec /home/wurfkreuz/Downloads/archives/GoLand-252.19874.29/bin/goland'
# swaymsg 'exec foot tmux'
sleep 4
# Can't use this code with the sway tmux float. Otherwise the float will open with the main function instead of the one i specify.
# You also need to use the 'exec foot tmux new-session -d -s main || true' command
swaymsg 'exec foot tmux new-session -d -s main || true'
sleep 2
# swaymsg 'exec /usr/bin/foot /usr/bin/tmux run-shell /home/wurfkreuz/.tmux/plugins/tmux-resurrect/scripts/restore.sh'
swaymsg 'exec foot tmux run-shell /home/wurfkreuz/.tmux/plugins/tmux-resurrect/scripts/restore.sh'
sleep 2
swaymsg 'exec foot tmux attach-session -t main'

# swaymsg 'layout stacking'

sleep 2
swaymsg 'layout tabbed'

# # Tab 1
# swaymsg 'workspace 3'
# swaymsg 'layout tabbed'

# # swaymsg 'exec alacritty -e zellij attach main'
# # swaymsg 'exec alacritty -e zellij'
# swaymsg 'exec foot tmux'
# # swaymsg 'exec foot ~/.cargo/bin/zellij'
# # swaymsg 'exec foot zellij'
# # swaymsg 'exec ghostty -e zellij'
# # swaymsg 'exec alacritty -e tmux'

# # # Wait for Emacs to launch
# sleep 2

# # # Split the layout vertically, launch Alacritty, and set layout to stacking
# swaymsg 'splitv'
# # swaymsg 'exec /home/wurfkreuz/.nix-profile/bin/emacs'
# swaymsg 'exec emacs'
# # swaymsg exec '/home/wurfkreuz/common-lisp/lem/lem --interface "sdl2"'
# # swaymsg 'exec emacs --eval "(load-desktop-session \"main\")"'
# swaymsg 'layout stacking'

sleep 1


swaymsg 'workspace 4'
# swaymsg 'exec telegram-desktop'
# swaymsg 'exec Telegram'
swaymsg 'exec /snap/bin/telegram-desktop'

sleep 1

# swaymsg 'workspace 5'

# swaymsg 'exec obsidian'

# sleep 5

swaymsg 'workspace 3'


# /home/wurfkreuz/.dotfiles/scripts/sh/clean-zellij >> /home/wurfkreuz/.var/log/zellij/zellij.log 2>&1
