#!/usr/bin/env sh

# Your existing script to set up workspaces and launch applications
# Create a tabbed container on workspace 1 and assign Alacritty instances to it
swaymsg 'workspace 1'
# swaymsg 'layout tabbed'
# swaymsg 'exec opera --enable-features=UseOzonePlatform --ozone-platform=wayland'
# swaymsg 'exec opera'
swaymsg 'exec firefox'

sleep 2

# Create a tabbed container on workspace 2 and assign browsers to it
swaymsg 'workspace 2'
# swaymsg 'layout tabbed'
# swaymsg 'exec vivaldi-stable'
# swaymsg 'exec vivaldi.vivaldi-stable'
# swaymsg 'exec librewolf-wayland'
swaymsg 'exec librewolf'
# swaymsg 'exec vivaldi --enable-features=UseOzonePlatform --ozone-platform=wayland'
# swaymsg 'exec alacritty'

sleep 2


swaymsg 'workspace 3'
# swaymsg 'exec foot ~/.cargo/bin/zellij attach main'
# swaymsg 'exec foot tmux new-session -d "tmux run-shell ~/.tmux/plugins/tmux-resurrect/scripts/restore.sh" \; attach'

swaymsg 'exec alacritty -e tmux'
# # You also need to use the 'exec foot tmux new-session -d -s main || true' command
# # Can't use this code with the sway tmux float. Otherwise the float will open with the main function instead of the one i specify.
# swaymsg 'exec foot tmux new-session -d -s main || true'
# sleep 1
# # swaymsg 'exec /usr/bin/foot /usr/bin/tmux run-shell /home/wurfkreuz/.tmux/plugins/tmux-resurrect/scripts/restore.sh'
# swaymsg 'exec foot tmux run-shell /home/wurfkreuz/.tmux/plugins/tmux-resurrect/scripts/restore.sh'
# sleep 1
# swaymsg 'exec foot tmux attach-session -t main'

# swaymsg 'tmux new-session -d "tmux run-shell ~/.tmux/plugins/tmux-resurrect/scripts/restore.sh"'
# swaymsg 'exec ghostty'


sleep 2

swaymsg 'workspace 4'
# swaymsg 'exec telegram-desktop'
# swaymsg 'exec telegram'
swaymsg 'exec /home/wurfkreuz/Downloads/Telegram/Telegram'

swaymsg 'workspace 3'


# /home/wurfkreuz/.dotfiles/scripts/sh/clean-zellij >> /home/wurfkreuz/.var/log/zellij/zellij.log 2>&1
