#!/bin/bash

set -e

password=$(kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d)

echo $password | wl-copy

echo -e "The password is copied to your clipboard:\n$password"
