#!/bin/bash

set -e

password=$(kubectl get secret my-awx-instance-admin-password -n awx -o jsonpath="{.data.password}" | base64 --d)

echo $password | wl-copy

echo -e "The password is copied to your clipboard:\n$password"
