#!/bin/sh

set -e

sudo apt install autoconf texinfo imagemagick libmagickwand-dev libgtk-3-dev libglib2.0-dev libgccjit0 libgccjit-13-dev libgnutls28-dev libtree-sitter-dev

CC=gcc-14 ./autogen.sh

./configure --with-native-compilation=aot --with-tree-sitter  --with-gif \
--with-png --with-jpeg --with-rsvg --with-tiff  --with-imagemagick \
--with-pgtk --with-mailutils 

make -j$(nproc)

# I often don't install the compiled binary
# sudo make install
