#!/bin/sh

# Recheck if you've added all the echo redirections (and i need to use >>
# instead of >)

repos="$HOME/.dotfiles $HOME/.emacs.d"
main_hash=""
log_file=""

delimiter() {
    echo "=================================================================\n"
}

check_log_file() {
    if [ -f "$HOME/.secret_dotfiles/logs/git-mirror.log"]; then
        touch "$HOME/.secret_dotfiles/logs/git-mirror.log"
        log_file="$HOME/.secret_dotfiles/logs/git-mirror.log"
    else
        continue
    fi
}

gitlab_remote_check() {
    remote_output="$(git remote -v | awk '{print $1}' | grep -E '^gitlab$')" || \
        { echo "The remote with the name 'gitlab' doesn't exist."; exit 1; }
}

main() {
    for repo in $repos; do
        check_log_file
        [ -d "$repo" ] || { echo "$(date)\nDirectory $repo doesn't exist.\n\n" > ; exit 1; }
        main_hash="$(git ls-remote origin master)"
        mirror_hash="$(git ls-remote gitlab master)"
        if [ mirror_hash != main_hash ]; then
            gitlab_remote_check
            cd "$repo" && git push gitlab master
        else
            $(date) > "$log_file"
            echo "Nothing to push for $repo"
            delimiter
        fi
    done
}

case "$(basename "$0")" in
    git-mirror) main;;
esac
