#!/bin/bash

set -e

password=$(kubectl get secret grafana --namespace default -o jsonpath='{.data.admin-password}' | base64 --decode)

echo $password | wl-copy

echo -e "The password is copied to your clipboard:\n$password"
