#!/bin/bash

HELP_DIR=$HOME/.dotfiles/scripts/sh/help-files
FLAGS_DIR=$HELP_DIR/flags

search() {
    file_path="$TARGET_DIR/$1.txt"
	echo "This is file path: $file_path"
	# Try the original file -E
	if ! cat "$file_path" 2> /dev/null; then
		# Try adding 's'
		file_path="$1s.txt"
		if ! cat "$file_path" 2> /dev/null; then
			# Try removing the last character (using `expr` instead of `${var%?}`)
			trimmed_arg=$(echo "$1" | sed 's/.$//')
			file_path="$trimmed_arg.txt"
			if ! cat "$file_path" 2> /dev/null; then
				echo "No entry for $1"
				exit 1
			fi
		fi
	fi
}

show_docs() {
    file_path="$HELP_DIR/$1.txt"

	if [ "$1" = "psql" ]; then
		file_path="$HELP_DIR/postgres.txt"
		cat "$file_path"
    else
		search $1
    fi
}

show_flags() {
    file_path="$HELP_DIR/flags/$1.txt"

	if [ "$1" = "psql" ]; then
		file_path="$HELP_DIR/postgres.txt"
		cat "$file_path"
    else
		search $1
    fi
}

edit_help() {
	if [ -z "$EDITOR" ]; then
		echo "The EDITOR variable isn't set" && exit 1
	else
		"$EDITOR" "$HELP_DIR/$1.txt"
	fi
}

main() {
	case "$1" in
		-e) shift
			edit_help "$@";;
		-f) shift
			TARGET_DIR=$FLAGS_DIR; show_flags "$@";;
		*) TARGET_DIR=$HELP_DIR; show_docs "$@";;
	esac
}

case "$(basename "$0")" in
    h) main "$@";;
esac
