#!/bin/bash

printf "\nFor complex ansible playbooks it is better to use a modular approach
of creating a collection and connecting smaller pieces with each other.
To create a collection use 'ansible-galaxy collection init namespace.collection_name',
where the namespace is a identifier that shows origins of a collection.
 For example:

johndoe - a person's name
ansible - identifies collections made by Ansible
mycompany - collections from mycompany

Where a collection_name is just a name for a collection.

A full command looks like this:

ansible-galaxy collection init namespace.collection_name


If you are in a collection directory, this is an example of how 
to add roles 

ansible-galaxy init --init-path=roles setup_git_ssh

Playbooks in role directories are written in a 'tasks' directory
in a main.yml file."
