#!/bin/sh

wl_paste_output=$(wl-paste -l | head -n 1)

echo "This is the first line of the wl-paste output: $wl_paste_output"

type=${wl_paste_output%/*}

echo $type

if [ ! $type = "image" ]; then
	echo "Incorrect type, want \"image\", got $type."
else
	echo "$($HOME/.secret_dotfiles/)"
