#!/bin/bash

# # mapfile -t NAMES < <(zellij list-sessions | awk '($1 ~ /-/) {print $1}')
# zellij list-sessions | awk '($1 ~ /-/) {print $1}' | mapfile -t NAMES


# for name in $NAMES; do
#     echo "This is a session name: $name"
# done

# Use the pipeline to fill the NAMES array
zellij list-sessions | awk '($1 ~ /-/) {print $1}' | mapfile -t NAMES

# Iterate over the elements of the NAMES array
for name in "${NAMES[@]}"; do
    echo "This is a session name: $name"
done


# Why do i need '<()'?
# The mapfile works with file descriptors and '<()' emulates having a temporary file.
# The core purpose of mapfile is to read lines of input (whether from files or
# other sources) and efficiently populate a Bash array.
