#!/bin/bash

# Define the source directories
DOTFILES_DIR="$HOME/.dotfiles"
SECRET_DOTFILES_DIR="$HOME/.secret_dotfiles"
CONFIG_DIR="$HOME/.config"

# Array of files/directories to symlink
declare -A FILES_TO_SYMLINK=(
    [".zshrc"]="$HOME/.zshrc"
    ["nvim"]="$CONFIG_DIR/nvim"
    ["alacritty/alacritty.toml"]="$CONFIG_DIR/alacritty/alacritty.toml"
    ["zellij/config.kdl"]="$CONFIG_DIR/zellij/config.kdl"
    ["k9s"]="$CONFIG_DIR/k9s"
    [".ssh"]="$HOME/.ssh"
)

# Function to create a symlink
create_symlink() {
    local source="$1"
    local target="$2"

    if [ -e "$target" ] || [ -L "$target" ]; then
        read -p "File or directory $target already exists. Do you want to delete it and create a symlink? (y/n): " choice
        if [ "$choice" == "y" ]; then
            rm -rf "$target"
            echo "Deleted $target"
        else
            echo "Skipped $target"
            return
        fi
    fi

    ln -s "$source" "$target"
    echo "Created symlink: $target -> $source"
}

# Iterate over the files/directories and create symlinks
for file in "${!FILES_TO_SYMLINK[@]}"; do
    if [ "$file" == ".ssh" ]; then
        source_path="$SECRET_DOTFILES_DIR/$file"
    else
        source_path="$DOTFILES_DIR/$file"
    fi
    target_path="${FILES_TO_SYMLINK[$file]}"

    if [ -e "$source_path" ]; then
        create_symlink "$source_path" "$target_path"
    else
        echo "Source $source_path does not exist. Skipping."
    fi
done
