#!/bin/sh


cd ~/test
input="$(find . | sort )"
echo "This is input: \n$input\n"

find . | sort | while IFS= read line; do
if [ "$line" = "." ]; then
	continue
else
	line_count="$(echo "$line" | wc -m)"
	truncated_line="$(echo $line | sed 's/\.\/.*\///')"
	truncated_line_count="$(echo "$truncated_line" | wc -m)"
	difference="$(expr "$line_count" - "$truncated_line_count")"
	spaces=""

	for i in $(seq $difference); do 
		spaces="$spaces "
	done
	processed_line="$spaces|____$truncated_line"
	if [ "$(echo "$processed_line" | cut -c1)" = " " ]; then
		# echo "The line starts with a whitespace, a pipe should be added."
		processed_line="|$processed_line"
		echo "$processed_line"
	else
		# echo "The line doesn't start with a whitespace."
		echo "$processed_line"
	fi
	count=1
	echo "This is value of the count befor the if condition: $count"
	if [ "$count" = "1" ]; then
		echo "This is the first line: $processed_line"
	else
		echo "This is not the first line"
	fi
fi
count="$(expr "$count" + 1)"
echo "Current count: $count"
done





# .
# ./config
# ./config/config321
# ./config/config321/test1337
# ./config/config321/test69
# ./config/file1
# ./config/file2
# ./config/recursive_dir
# ./config/recursive_dir/rec-file1
# ./config/recursive_dir/rec-file2
# ./init.lua
# ./lazy-lock.json
# ./test-file.bak
# ./test-file2
# ./testfile.md
#
#
# .
# |___config
# |___|___config321
# |___|___|___test1337
# |___|___|___test69
# |___|___file1
# |___|___file2
# |___|___recursive_dir
# |___|___|___rec-file1
# |___|___|___rec-file2
# |___init.lua
# |___lazy-lock.json
# |___test-file.bak
# |___test-file2
# |___testfile.md
#
#
#
#
#
#
#
# |___config
# |___|___config321
# |___|___|___test1337
# |___|___|___|___deeply_nested
# |___|___|___|___|___level2
# |___|___|___|___|___|___level3
# |___|___|___|___|___|___|___level4
# |___|___|___|___|___|___|___|___level5_file.txt
# |___|___|___|___test69
# |___|___|___|___another_dir_in_69
# |___|___|___|___|___yet_another_level
# |___|___file1
# |___|___|___file2
# |___|___|___recursive_dir
# |___|___|___|___nested_dir
# |___|___|___|___|___very_nested
# |___|___|___|___|___|___even_more_nested
# |___|___|___|___|___|___|___deep_file.lua
# |___|___|___|___rec-file1
# |___|___|___|___rec-file2
# |___init.lua
# |___lazy-lock.json
# |___test-file.bak
# |___test-file2
# |___testfile.md
#
#
# # Delete '___|' if it's followed by '___|'
# # Delete '___|___' if it's followed by '|___'
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
