#!/bin/bash


set -e


if [[ -z $VAULT_ADDR ]]; then
    echo "Enter vault address:"
    read -r VAULT_ADDR
    export VAULT_ADDR="$VAULT_ADDR"
fi


if vault policy list -address $VAULT_ADDR &> /dev/null; then
    echo "You are logged in"
else
    echo "You are not logged in"
    echo "Enter the root token to authenticate:"
    read -r TOKEN
    vault login -address $VAULT_ADDR $TOKEN
fi

echo "Enter path for kubeconfig file:"
read -r KUBECONFIG
if [[ ! -f $KUBECONFIG ]]; then
    echo "The kubeconifg file doesn't exist."; exit 1
fi

echo "Enter the path that comes after the value for the '-mount' flag (it's
shown as the second parameter of the CLI path):"
read -r MOUNT_PATH 

echo "Enter cluster alias:"
read -r ALIAS

echo "Enter prefix for generating names of key values:"
read -r PREFIX

API_SERVER_URL="$(yq -r '.clusters[0].cluster."server"' "$KUBECONFIG")"
CA_DATA="$(yq -r '.clusters[0].cluster."certificate-authority-data"' "$KUBECONFIG")"
CLIENT_CERT_DATA="$(yq -r '.users[0].user."client-certificate-data"' "$KUBECONFIG")"
CLIENT_KEY_DATA="$(yq -r '.users[0].user."client-key-data"' "$KUBECONFIG")"

vault kv put -mount="kv" "$MOUNT_PATH" \
    "${PREFIX}api_server_url"="$API_SERVER_URL" \
    "${PREFIX}ca_data"="$CA_DATA" \
    "${PREFIX}client_cert_data"="$CLIENT_CERT_DATA" \
    "${PREFIX}client_key_data"="$CLIENT_KEY_DATA" \
    "${PREFIX}cluster_alias"="$ALIAS" 
