- name: Get the name of the main user
  ansible.builtin.shell: "awk -F: '$3 == 1000 {print $1}' /etc/passwd"
  register: main_user
  changed_when: false

- name: Create .ssh directory in the home directory of the main user
  ansible.builtin.file:
    path: "/home/{{ main_user.stdout }}/.ssh"
    state: directory
    mode: '0700'
    owner: "{{ main_user.stdout }}"
    group: "{{ main_user.stdout }}"

- name: Create subdirectory 'keys' in the .ssh directory
  ansible.builtin.file:
    path: "/home/{{ main_user.stdout }}/.ssh/keys"
    state: directory
    mode: '0700'
    owner: "{{ main_user.stdout }}"
    group: "{{ main_user.stdout }}"

- name: Create the ssh config file
  ansible.builtin.file:
    path: "/home/{{ main_user.stdout }}/.ssh/config"
    state: file
    mode: '644'

- name: Generate ssh key
  ansible.builtin.command: "ssh-keygen -t rsa -b 2048 -f /home/{{ main_user.stdout }}/.ssh/keys/git -q -N ''"
  args:
    creates: "/home/{{ main_user.stdout }}/.ssh/keys/git"
  become: true
  become_user: "{{ main_user.stdout }}"

- name: Fill the ssh config file
  ansible.builtin.blockinfile:
    path: "/home/{{ main_user.stdout }}/.ssh/config"
    block: |
      Host *
          ServerAliveInterval 60
          ServerAliveCountMax 5

      Host github.com
          IdentityFile ~/.ssh/keys/git

      Host gitlab.com
          IdentityFile ~/.ssh/keys/git
    owner: "{{ main_user.stdout }}"
    group: "{{ main_user.stdout }}"
    mode: '0644'

- name: Add name credential of the main user to git
  ansible.builtin.command: 'git config --global user.name "wurfkreuz"'

- name: Add email credential of the main user to git
  ansible.builtin.command: 'git config --global user.email "wurfkreuz@mail.ru"'

- name: Cat a file
  ansible.builtin.command: cat /home/{{ main_user.stdout }}/.ssh/keys/git.pub
  register: file_content
  changed_when: false

- name: Print file content
  ansible.builtin.debug:
    msg: "{{ file_content.stdout }}"


# 'creates' serves as a condition that tells Ansible to skip the command execution if the specified file or directory already exists.
