#!/bin/env python

import requests

server_url = "http://127.0.0.1:8000/create_record"
headers = {"Content-Type": "application/json"}

print("Name of the flashcard:\n=> ", end="")
flashcard_name = input()

print("Provide the question:\n=> ", end="")
question = input()

print("Provide the answer:")
answer = input()

# request_body = f'{{"name":"{flashcard_name}", "question":"{question}", "answer":"{answer}"}}'
request_body = {
        "name": flashcard_name,
        "question": question,
        "answer": answer,
        }

response = requests.post(url=server_url, json=request_body, headers=headers)

print(f"This is the status code: {response.status_code}")
print(f"This is the response: {response.text}")

# print(f"This is the request body {request_body}")


