#!/bin/env python

import os
import sys

directory = sys.argv[1]
dirs_file = os.path.join(os.environ["HOME"], ".dotfiles/scripts/python/script_files/d_dirs")

def add_dir(directory, dirs_file):
    # Can't use 'w', because it erases the file making it unreadable
    with open(dirs_file, "r") as f:
        # The idea here is that i create a set of lines. The point of this
        # condition 'if line.strip()' is that i add only non-empty line to a
        # set. Because if the line is empty, then stripping returns nothing
        # because it remove the newline and any whitespaces an empty line might
        # have, hence the condition makes sense. If there is something left
        # after stripping, that means the line wasn't empty in the first place
        # and it is added to the set.
        # Additionally set is an unordered collection of unique elements,
        # meaning it will automatically do the sorting for me.
        # lines = {line.strip() for line in f if line.strip()}
        lines = {line.strip() for line in f if line.strip()}
        lines.add(directory.strip())
    with open(dirs_file, "w") as f:
        f.writelines(f"{line}\n" for line in lines)


def main():
    add_dir(directory, dirs_file)
    os.chdir(directory)


if __name__ == "__main__":
    main()

    
