#!/bin/python

import os


home_dir = os.getenv("HOME")
script_dir = os.getcwd()

def get_path(path, tail):
    dir_path = path + tail
    if os.path.isdir(dir_path):
        return dir_path
    else:
        print(f"Directory {dir_path} doesn't exist.\nCheck the script placement relative to session directories.")
        exit()

unsure_sesh_dir = get_path(script_dir, "/fleshcards_dir/session/s_unsure")
learned_sesh_dir = get_path(script_dir, "/fleshcards_dir/session/s_learned")
not_learned_sesh_dir = get_path(script_dir, "/fleshcards_dir/session/s_not_learned")

unsure_dir = get_path(script_dir, "/fleshcards_dir/session/s_unsure")
learned_dir = get_path(script_dir, "/fleshcards_dir/session/s_learned")
not_learned_dir = get_path(script_dir, "/fleshcards_dir/session/s_not_learned")

# print(f"This is {unsure_sesh_dir}")


