[package]
name = "update_dependencies"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "update_dependencies"
path = "src/main.rs"

[dependencies]
teloxide = { version = "0.12", features = ["macros"] }
log = "0.4"
pretty_env_logger = "0.4"
tokio = { version =  "1.8", features = ["rt-multi-thread", "macros"] }
