alerting:  # Main section for alert configuration
  alertmanagers:
    - static_configs:
        - targets:
            - localhost:9093 # Assuming you have the default alertmanager setup
  receivers:
    - name: 'aws-notifications'
      webhook_configs:
        - url: 'https://api.telegram.org/bot$NOTIFY_TOKEN/sendMessage'
          send_resolved: true
          max_alerts: 0
          http_config:
            bearer_token: $NOTIFY_TOKEN
