#!/bin/sh

# > cd-add .dotfiles
# This is the executed command: echo /home/wurfkreuz//home/wurfkreuz/.dotfiles >> /home/wurfkreuz/.dirs

# Secondly, i need to check if the added path exists.

dirs_path=""

clean_file() {
    temp_file=$(mktemp) || exit 1
    dir_file="$HOME/.dotfiles/scripts/sh/cd-add/.dirs"
    # NF is 'number of fields'. Don't forget that field in awk is a symbol
    # separated by whitespaces.
    awk 'NF > 0' "$dir_file" | sort -d | uniq > "$temp_file"
    mv "$temp_file" "$dir_file"
}

main() {
	# The -h flag is for cheking symlinks (the man page says about the -l flag also, but it doesn't work)
    if [ -e "$HOME"/.dirs ] && [ ! -h "$HOME"/.dirs ]; then
		echo "Can't symlink the \"~/.dotfiles/scripts/sh/cd-add/.dirs\". You already have a file or directory with the name '.dirs'."; exit 1;
    elif [ ! -e "$HOME"/.dirs ]; then
        ln -s "$HOME/.dotfiles/scripts/sh/cd-add/.dirs" "$HOME"
    fi

    # If i don't give any parameter
    if [ -z "$1" ]; then
        dirs_path=$(pwd)
        echo "$dirs_path" >> "$HOME"/.dirs
		echo "This is the executed command: echo $1 >> $HOME/.dirs"
        echo "$dirs_path is added."
    # If i write a full path for some reason with '/home...' or "~/", then i
    # just insert the given path.
    elif [ "$(echo "$1" | cut -c -5)" = "/home" ]; then
		dirs_path="$1"
		[ -d "$dirs_path" ] || { echo "Path $dirs_path doesn't exist."; exit 1; }
        echo "$1" >> "$HOME"/.dirs
		echo "This is the executed command: echo $1 >> $HOME/.dirs"
        echo "$1 is added."
    # If the given parameter doesn't exist and the logic implies, that i just
    # gave an unfull path
    elif [ ! -f "$1" ]; then
        dirs_path="$(pwd)/$1"
		[ -d "$dirs_path" ] || { echo "Path $dirs_path doesn't exist."; exit 1; }
        echo "$(pwd)/$1" >> "$HOME"/.dirs
		echo "This is the executed command: echo $(pwd)/$1 >> $HOME/.dirs"
        echo "$(pwd)/$1 is added."
    else
        echo "$1" >> "$HOME"/.dirs 
		echo "This is the executed command: echo $1 >> $HOME/.dirs"
        echo "$1 is added."
    fi
}

case "$(basename "$0")" in
    cd-add)
        main "$1"
        ;;
esac

