#!/bin/sh

clean_file() {
    temp_file=$(mktemp) || exit 1
    dir_file="$HOME/.dirs"
    # NF is 'number of fields'. Don't forget that field in awk is a symbol
    # separated by whitespaces.
    awk 'NF > 0' "$dir_file" | sort -d | uniq > "$temp_file"
    rm "$dir_file"
    mv "$temp_file" "$dir_file"
}

cd_add() {
    if [ ! -f "$HOME"/.dirs ]; then
        touch "$HOME"/.dirs
    fi

    clean_file
    current_path="$1"
    # If i don't give any parameter
    if [ -z "$1" ]; then
        current_path=$(pwd)
        echo "$current_path" >> "$HOME"/.dirs
    # If i write a full path for some reason with '/home...' or "~/", then i
    # just insert the given path.
    elif [ "$(echo "$1" | cut -c -5)" = "/home" ]; then
        echo "$1" >> "$HOME"/.dirs
    # If the given parameter doesn't exist and the logic implies, that i just
    # gave an unfull path
    elif [ ! -f "$current_path" ]; then
        current_path="$(pwd)/$current_path"
        echo "$current_path" >> "$HOME"/.dirs
    else
        echo "$current_path" >> "$HOME"/.dirs 
    fi
}

main() {
    cd-add $1
}

case $0 in
    cd-add)
        main
        ;;
esac

