- hosts: localhost
  tasks:
    - name: main user
      command: 'awk -F: ''$3==1000 {print $1}'' /etc/passwd'
      register: muser

    - name: ssh directory for the main user
      file:
        path: /home/{{muser.stdout}}/.ssh
        state: directory
        owner: "{{muser.stdout}}"
        group: "{{muser.stdout}}"
        mode: '0700'

    - name: root ssh directory
      become: yes
      file: 
        path: /root/.ssh
        state: directory
        mode: '0700'

    - name: generate key for root 
      become: yes
      shell: 'ssh-keygen -f /root/.ssh/git -N ""'
      args:
        creates: /root/.ssh/git

    - name: copy the key to user
      become: yes
      copy:
        src: /root/.ssh/git
        dest: /home/{{muser.stdout}}/.ssh/
        owner: "{{muser.stdout}}"
        group: "{{muser.stdout}}"
        mode: '0600'
        remote_src: yes

    - name: ensure root ssh config file exists
      become: yes
      file:
        path: /root/.ssh/config
        state: touch

    - name: create config file (root)
      become: yes
      blockinfile:
        path: /root/.ssh/config
        block: |
          Host github.com
            IdentityFile /root/.ssh/git

          Host gitlab.com
            IdentityFile /root/.ssh/git

    - name: ensure user ssh config file exists
      file:
        path: /home/{{muser.stdout}}/.ssh/config
        state: touch
        owner: "{{muser.stdout}}"
        group: "{{muser.stdout}}"

    - name: create config file (muser)
      blockinfile:
        path: /home/{{muser.stdout}}/.ssh/config
        block: |
          Host *
            ServerAliveInterval 60
            ServerAliveCountMax 5

          Host github.com
            IdentityFile /home/{{muser.stdout}}/.ssh/git

          Host gitlab.com
            IdentityFile /home/{{muser.stdout}}/.ssh/git

    - name: change ownership of the config
      file:
        path: /home/{{muser.stdout}}/.ssh/
        owner: "{{muser.stdout}}"
        group: "{{muser.stdout}}"

    - name: add name credential of the main user to git
      command: 'git config --global user.name "wurfkreuz"'

    - name: add email credential of the main user to git
      command: 'git config --global user.email "wurfkreuz@mail.ru"'

    - name: add name credential of root to git
      command: 'sudo git config --global user.name "wurfkreuz"'

    - name: add email credential of root to git
      command: 'sudo git config --global user.email "wurfkreuz@mail.ru"'
