- name: Configure fresh Arch Linux install
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Synchronize package database and install packages
      community.general.pacman:
        name:
          - git
          - ninja
          - vim
          - vivaldi
          - alacritty
          - exa
          - zoxide
          - fzf
          - ninja
          - cmake
          - unzip
          - zellij
          - telegram-desktop
          - fd
          - ripgrep
          - wl-clipboard
          - ttf-noto-nerd
          - yamllint
          - ansible-lint
          - nodejs
          - npm
          - yaml-language-server
          - ansible-language-server
          - rustup
          - go
          - lua-language-server
          - opera
          - nushell
          - gopls
          - shellcheck
          - docker
          - docker-buildx
        state: latest
        update_cache: true
      become: true

    - name: Soft link directories
      vars:
        directories_to_link:
          - zellij
          - nvim
          - alacritty
          - hyprland
      ansible.builtin.file:
        src: "{{ ansible_env.HOME }}/.dotfiles/{{ item }}"
        path: "{{ ansible_env.HOME }}/.config"
        state: link
