- hosts: localhost
  tasks:

    - name: create the main user variable
      command: "awk -F: '($3 == 1000) {print $1}' /etc/passwd"
      register: main_user

    - name: check if nvim directory exists
      stat:
        path: '/home/{{ main_user.stdout }}/.config/nvim'
      register: nvim_dir

    - name: git clone
      git:
        repo: 'git@github.com:Doodler8888/nvim.git'
        dest: '/home/{{ main_user.stdout }}/.config/nvim'
      when: not nvim_dir.stat.exists

    - name: fetch users
      shell: 'awk -F: ''$3>=1001 && $1!="nobody" && $1!~/nixbld/ {print $1}'' /etc/passwd'
      register: users

    - name: copy files to user directories
      become: true
      copy:
        src: '/home/{{ main_user.stdout }}/.config/nvim'
        dest: '/home/{{ item }}/.config/nvim'
        owner: "{{ item }}"
        group: "{{ item }}"
        mode: '0744'
      loop: "{{ users.stdout_lines }}"

    - name: copy to root dir
      become: true
      copy:
        src: '/home/{{ main_user.stdout }}/.config/nvim'
        dest: '/root/.config/'
