[[bin]]
name = "my_binary"
path = "src/main.rs"

[package]
name = "shelf_bot"
version = "0.1.0"
edition = "2021"

[dependencies]
teloxide = { version = "0.12", features = ["macros"] }
pretty_env_logger = "0.4"
log = "0.4"
tokio = { version = "1.9", features = ["rt-multi-thread", "macros"] }
simple_logger = "1.1"

[features]
default = ["feature1"]
feature1 = []
feature2 = ["dep1", "dep2"]
